# Action that request a trajectory for reaching a given grasping pose

# Goal
geometry_msgs/TransformStamped grasping_pose
string arm      # Do I need to specify the arm here??
---
# Result
geometry_msgs/PoseStamped[] trajectory 
---
# Feedback
string sim_status
geometry_msgs/PoseStamped[] sim_trajectory
