%YAML:1.0
t_0:
    - marker: 0
      size: 28.5
      keep: true

t_1:
    - marker: 1
      size: 28.5
      keep: true

t_2:
    - marker: 2
      size: 28.5
      keep: true

t_3:
    - marker: 3
      size: 28.5
      keep: true
